name: flame_rive_example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0-releasecandidate.1

environment:
  sdk: ">=2.15.0-157.0.dev <3.0.0"


dependencies:
  rive: 0.7.30
  flame: ^1.0.0-releasecandidate.15
  flame_rive: 1.0.0-releasecandidate.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
